### ISSUE TITLE
Error on eval: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by abreumatheus** [tonsky/Clojure-Sublimed#100]
I'm encountering the following error on the console while trying to do any type of eval.
I'm on nREPL 1.0.0 and the latest version of both Sublime and Clojure Sublimed.

The following was trying to eval `(+ 1 2)`:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 202, in exception_handler
    return event_handler(*args)
  File "/Users/matheus.abreu/Library/Application Support/Sublime Text/Installed Packages/Clojure Sublimed.sublime-package/cs_eval.py", line 422, in on_text_changed_async
    erase_evals(should_erase, view)
  File "/Users/matheus.abreu/Library/Application Support/Sublime Text/Installed Packages/Clojure Sublimed.sublime-package/cs_eval.py", line 202, in erase_evals
    eval.erase()
  File "/Users/matheus.abreu/Library/Application Support/Sublime Text/Installed Packages/Clojure Sublimed.sublime-package/cs_eval.py", line 163, in erase
    if interrupt and self.status == "pending" and self.session:
AttributeError: 'Eval' object has no attribute 'status'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1704, in run_
    return self.run(edit)
  File "/Users/matheus.abreu/Library/Application Support/Sublime Text/Installed Packages/Clojure Sublimed.sublime-package/cs_eval.py", line 300, in run
  File "/Users/matheus.abreu/Library/Application Support/Sublime Text/Installed Packages/Clojure Sublimed.sublime-package/cs_conn.py", line 56, in eval
  File "/Users/matheus.abreu/Library/Application Support/Sublime Text/Installed Packages/Clojure Sublimed.sublime-package/cs_eval.py", line 53, in __init__
  File "/Users/matheus.abreu/Library/Application Support/Sublime Text/Installed Packages/Clojure Sublimed.sublime-package/cs_progress.py", line 62, in phase
  File "/Users/matheus.abreu/Library/Application Support/Sublime Text/Installed Packages/Clojure Sublimed.sublime-package/cs_progress.py", line 26, in phase
TypeError: 'NoneType' object is not subscriptable
```

**Comment by tonsky** [comment]
Interesting! I can’t reproduce this. Can you

1. Go to Preferences: Clojure Sublimed Settings
2. Add `"debug": true,`
3. Connect, eval, get this exception
4. Send me the content of console (ctrl+`)

**Comment by abreumatheus** [comment]
Great, now I can't reproduce it too 🤣.
I guess it's fixed then hahaha
