### ISSUE TITLE
Clojure Sublimed fails to initialize: cs_conn has no attribute 'Connection' (most likely due to a circular import)

### ISSUE THREAD

**Issue by einars** [tonsky/Clojure-Sublimed#107]
Introduced by changes in eba74459fa55381b0f20d31b9b41f9c48f2c88f8, the plugin fails to load,

```
...
reloading plugin Clojure Sublimed.cs_common
reloading plugin Clojure Sublimed.cs_conn
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/e/.config/sublime-text/Packages/Clojure Sublimed/cs_conn.py", line 2, in <module>
    from . import cs_common, cs_eval, cs_eval_status, cs_parser, cs_warn
  File "/home/e/.config/sublime-text/Packages/Clojure Sublimed/cs_eval.py", line 3, in <module>
    from . import cs_common, cs_conn, cs_eval_status, cs_parser, cs_printer, cs_progress, cs_watch
  File "/home/e/.config/sublime-text/Packages/Clojure Sublimed/cs_watch.py", line 2, in <module>
    from . import cs_common, cs_conn, cs_conn_socket_repl, cs_parser, cs_printer
  File "/home/e/.config/sublime-text/Packages/Clojure Sublimed/cs_conn_socket_repl.py", line 18, in <module>
    class ConnectionSocketRepl(cs_conn.Connection):
AttributeError: partially initialized module 'Clojure Sublimed.cs_conn' has no attribute 'Connection' (most likely due to a circular import)
reloading plugin Clojure Sublimed.cs_conn_nrepl_jvm
...
```

Sublime Text Stable, build 4169 on Arch Linux, installed from https://download.sublimetext.com/arch/stable/x86_64 repository

**Comment by tonsky** [comment]
Thanks! Should be fixed in fb28ab5c232e6172760e1275d8b364cf1c9db949
