### ISSUE TITLE
Unable to see eval output on Sublime 3

### ISSUE THREAD

**Issue by shellandbull** [tonsky/Clojure-Sublimed#109]
Hello There!

Whenever I try to `Clojure Sublime: Evaluate` I see the following error on my sublime console

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1704, in run_
    return self.run(edit)
  File "/Users/xyzxyz/Library/Application Support/Sublime Text 3/Installed Packages/Clojure Sublimed.sublime-package/cs_eval.py", line 297, in run
  File "/Users/xyzxyz/Library/Application Support/Sublime Text 3/Installed Packages/Clojure Sublimed.sublime-package/cs_conn_socket_repl.py", line 106, in eval
  File "/Users/xyzxyz/Library/Application Support/Sublime Text 3/Installed Packages/Clojure Sublimed.sublime-package/cs_eval.py", line 53, in __init__
  File "/Users/xyzxyz/Library/Application Support/Sublime Text 3/Installed Packages/Clojure Sublimed.sublime-package/cs_progress.py", line 62, in phase
  File "/Users/xyzxyz/Library/Application Support/Sublime Text 3/Installed Packages/Clojure Sublimed.sublime-package/cs_progress.py", line 26, in phase
TypeError: 'NoneType' object is not subscriptable
```

I am on

```
MacOS Sonoma 14.4.1
Sublime Build 4169
```

**Comment by tonsky** [comment]
Weird, I was able to reproduce it once when installing it from Package Control but then I wasn’t able to reproduce it second time. Anyway, I added some defensive coding, hope it helps. Try 3.7.2

**Comment by tonsky** [comment]
Did it work?

**Comment by sander** [comment]
See also https://github.com/tonsky/Clojure-Sublimed/issues/100

I’ve had the same issue on a fresh installation. After setting `"debug": true` and restarting Sublime Text to debug, it seems fixed.

**Comment by shellandbull** [comment]
@tonsky / @sander thanks for following up but I decided to switch to emacs and use the corgi setup, where I found a bug too but we found a fix for it as well ❤️ thanks everyone!

**Comment by tonsky** [comment]
Meanwhile I was able to reproduce it while working on another issue, tried to fix this again. If anyone is still interested, try 3.7.3

**Comment by sander** [comment]
Works for me, thank you @tonsky!
