### ISSUE TITLE
toggle_info_command exception for eval results (phantom_success_fg=None)

### ISSUE THREAD

**Issue by einars** [tonsky/Clojure-Sublimed#91]
Attempting to toggle_info_command on eval results doesn't work for me, something is off with the color style definitions, console with some of debug:

```
toggle_info_command for eval status=success
Eval.colors = {'pending': ('region.bluish', '#7a3e9d'), 'interrupt': ('region.bluish', '#7a3e9d'), 'success': ('region.greenish', '#6abf40'), 'exception': ('region.redish', '#cc3333'), 'lookup': ('region.bluish', '#7a3e9d'), 'phantom_success_fg': None, 'phantom_success_bg': None, 'phantom_exception_fg': None, 'phantom_exception_bg': None}
scope_color: returning None for scope phantom_success_fg
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 1703, in run_
    return self.run(edit)
  File "/home/e/.config/sublime-text/Packages/Clojure-Sublimed/cs_eval.py", line 364, in run
    eval.toggle_pprint()
  File "/home/e/.config/sublime-text/Packages/Clojure-Sublimed/cs_eval.py", line 137, in toggle_pprint
    if phantom_styles := self.phantom_styles("phantom_success"):
  File "/home/e/.config/sublime-text/Packages/Clojure-Sublimed/cs_eval.py", line 121, in phantom_styles
    _, fg = self.scope_color(f"{scope}_fg")
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by tonsky** [comment]
Yeah, sorry about that
